# Kalıcılık
appendonly yes
appendfsync everysec

# Performans
maxmemory 4gb
maxmemory-policy allkeys-lru

# Güvenlik
requirepass canwia123
rename-command FLUSHALL ""
rename-command CONFIG ""

# Limitler
timeout 300
tcp-keepalive 60
maxclients 10000