spring.application.name=exchangeAPIv1

  # Root log seviyesi
logging.level.root=INFO

# Kendi paketini DEBUG yap
logging.level.com.maf.exchangeapiv1=DEBUG

# WebSocket loglar?n? görmek için
logging.level.com.maf.exchangeapiv1.handler=DEBUG

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 DB Connection Settings
spring.datasource.url=jdbc:h2:mem:exchange_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Redis Configuration
# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=canwia123
spring.data.redis.timeout=2000ms


# Redis Lettuce Pool
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0



API_KEY=${API_KEY}
PASSPHRASE=${PASSPHRASE}
API_SECRET=${API_SECRET}