spring.application.name=exchangeAPIv1

  # Root log seviyesi
logging.level.root=INFO

# Kendi paketini DEBUG yap
logging.level.com.maf.exchangeapiv1=DEBUG

# WebSocket loglar?n? görmek için
logging.level.com.maf.exchangeapiv1.handler=DEBUG


spring.datasource.url=jdbc:postgresql://localhost:5432/exchange_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=canwia123
spring.data.redis.timeout=2000ms


# Redis Lettuce Pool
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0



# Google OAuth2 Client
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# Base URL (Uygulaman?z?n çal??t??? adres)
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

# JWT Ayarlar?
app.jwt.secret=${JWT_SECRET_KEY}
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

# Coinbase Exchange API
API_KEY=${API_KEY}
PASSPHRASE=${PASSPHRASE}
API_SECRET=${API_SECRET}

API_KEY_BINANCE = ${API_KEY_BINANCE}
API_SECRET_BINANCE = ${API_SECRET_BINANCE}